"""
 6634 - Cryptography
 Name: Patrick Silver
 Date: 4/21/23
 Description: HW3 Programming Problem (Question 5) 
 Implementation of DSA. Your program will take as input p, q, h, x, k, 
 a “real” value H(M1), and a “fake” value H(M2) (which will be different from H(M1))
 Follows the equations on wk10_DSA.pdf

Runs on three different example inputs:
1.   p = 7, q = 3, h = 3, x = 2, k = 1,H(M1) = 3,H(M2) = 4. 
2.  p = 103, q = 17, h = 13, x = 9, k = 6,H(M1) = 7,H(M2) = 3.
3.  An input generated by you - you should generate the largest values
    for which you can get correct results in a “reasonable” amount of time.
    p = 107
    q = 5
    h = 2
    x = 19
    k = 11
    H1 = 43123412169123
    H2 = 37234210981231
"""
import random

def DSA(p, q, h, x, k, real_H, fake_H):
    # 1) Calculate g and y, then print values
    g = pow(h, (p - 1) // q, p)  # pow(base, exponent, module)
    y = pow(g, x, p)
    print(f'g = {g}   y = {y}')

    # 2) Calculate the signature (r, s) for real_H, then print values
    r, s = 0, 0
    while r == 0 or s == 0:
        while True:
            k = random.randint(1, q - 1)  # get random k
            if k > 0:
                break
        r = pow(g, k, p) % q
        k_inv = pow(k, q - 2, q)
        s = (k_inv * (real_H + x * r)) % q
    print(f'r = {r}   s = {s}')

    # 3) Verify that (r, s) is the signature for real_H (H1)
    w = pow(s, q - 2, q)
    u1 = (real_H * w) % q
    u2 = (r * w) % q
    v = ((pow(g, u1, p) * pow(y, u2, p)) % p) % q
    if v == r:
        print('\nSignature verification for real_H (H1) successful: ')
    else:
        print('\nSignature verification for real_H failed: ')
    print(f'w: {w}   u1: {u1}   u2: {u2}   v: {v}')

    # 4) Verify signature (r, s) for fake_H (H2)
    w = pow(s, q - 2, q)
    u1 = (fake_H * w) % q
    u2 = (r * w) % q
    v = ((pow(g, u1, p) * pow(y, u2, p)) % p) % q
    if v == r:
        print('\nSignature verification for fake_H (H2) successful: ')
    else:
        print('\nSignature verification for fake_H (H2) failed: ')
    print(f'w: {w}   u1: {u1}   u2: {u2}   v: {v}')

# Example inputs and function calls
print("Example Input 1:")
p, q, h, x, k, real_H, fake_H = 7, 3, 3, 2, 1, 3, 4
DSA(p, q, h, x, k, real_H, fake_H)

print("\nExample Input 2:")
p, q, h, x, k, real_H, fake_H = 103, 17, 13, 9, 6, 7, 3
DSA(p, q, h, x, k, real_H, fake_H)

print("\nExample Input 3:")
p = 107
q = 5
h = 2
x = 19
k = 11
H1 = 43123412169123
H2 = 37234210981231
DSA(p, q, h, x, k, real_H, fake_H)
